
stages:
- name: Build
  inputs:
  - url: https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    working_dir: StoreWebApp
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      npm install
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: sreenivas@us.ibm.com
      space: dev
      application: bluecompute-web-tc
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -n "${CF_APP}" -d "${DOMAIN}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
