---
stages:
- name: Build
  inputs:
  - url: https://github.com/ssibm/refarch-cloudnative-bluecompute-web
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    working_dir: StoreWebApp
    build_type: npm
    script: |-
      #!/bin/bash
      npm install